In [4]:
# 1. Create a null vector of size 10 but the fifth value which is 1.

import numpy as np
a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [6]:
# 2. Create a vector with values ranging from 10 to 49.

a=np.random.randint(10,49,(3,3))
a

array([[14, 14, 16],
       [24, 16, 39],
       [46, 27, 42]])

In [11]:
# 3. Create a 3x3 matrix with values ranging from 0 to 8
a=np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
# 4. Find indices of non-zero elements from [1,2,0,0,4,0]
a=[1,2,0,0,4,0]
for i in range(len(a)): 
    if a[i]!=0:
        print(i,end=" ")

0 1 4 

In [15]:
# 5. Create a 10x10 array with random values and find the minimum and maximum values

a=np.random.randint(0,11,(10,10))
print("minimum : ",a.min())
print("maximum : ",a.max())

minimum :  0
maximum :  10


In [20]:
# 6. Create a random vector of size 30 and find the mean value.
a=np.random.randint(0,30,30)
a.mean()

14.6